styles/index.styl
styles/sw-popup.styl

feat: enhance the styls of SW-Update Popup

---

components/Header.vue
components/MobileHeader.vue
layouts/GlobalLayout.vue

A basic mobile menu prototype. Open to suggestions for any changes/revisions.

Mobile Menu Prototype

---

docs/README.md

Fix a grammatical error

---

index.js

fix: fix config for summary, summaryLength and pwa

---

components/Header.vue

fix: prevent nav from breaking into next line

---

docs/README.md
example/.vuepress/config.js
layouts/Post.vue
package.json

**Summary**
Bump blog plugin to v1.5.0 to support sitemap and commenting.

feat: support sitemap and commenting

---

components/Footer.vue
docs/README.md
example/.vuepress/config.js

**Summary**
I wanted to add GitLab to footer contact icons and ended up adding a few others I thought could be useful.
Cleanups are in relevant files and structured as atomic commits.
**Other …

feat: add several contact types

---

components/Footer.vue
docs/README.md
example/.vuepress/config.js

**Summary**
Needed codepen contact support. Saw this in the documentation.
> Welcome contribution of adding more built-in contact type.

codepen.io contact support

---

components/Newsletter.vue
example/.vuepress/config.js
layouts/Post.vue
package.json
yarn.lock

feat: support newsletter

---

layouts/FrontmatterKey.vue
layouts/GlobalLayout.vue
layouts/Post.vue

chore: fix id name typos

---

.eslintrc.js
components/Newsletter.vue
example/.vuepress/config.js
layouts/Post.vue
package.json
yarn.lock

**Summary**
It won't work fine If developer did not configure newsletter which means newsletter is disabled.
Fix by [vuepress-plugin-mailchimp](https://github.com/newsbielt703/vuepress-plugin-mailchimp/commit/53924c61b2cf236b2060eaf325ef6118bf136ff7).
To avoid wasting your time, it's best to open a **feature …

fix: disable newsletter causing crash

---

example/.vuepress/config.js
index.js

**Summary**
Currently, we have default blog plugin option as below:
```js
{
directories: [
{
id: 'post',
dirname: '_posts',
path: '/',
// layout: 'IndexPost', defaults to `Layout.vue`
itemLayout: 'Post',
itemPermalink: '/:year/:month/:day/:slug',
pagination: {
lengthPerPage: 5,
},
},
],
frontmatters: [
{
id: 'tag',
keys: ['tag', 'tags'],
path: '/tag/',
// layout: 'Tag',  defaults to `FrontmatterKey.vue`
frontmatter: { title: 'Tag' },
pagination: {
lengthPerPage: 5,
},
},
],
}
```
We can base on this plugin option set up the default navbar.
It'll be easier to start using this theme with more default configuration. 
**Does this PR …

feat: set up default nav

---

index.js
package.json
styles/font.styl
yarn.lock

Reverts vuepressjs/vuepress-theme-blog#43

revert: "fix: fonts are inaccessible (fix #40)"

---

docs/config/README.md
example/.vuepress/config.js
index.js
package.json
test/__snapshots__/config.spec.js.snap
yarn.lock

**Summary**
Same as default theme.

feat: smooth scroll

---

components/Header.vue
docs/config/README.md
example/.vuepress/config.js
index.js
package.json
yarn.lock

feat: support RSS, Atom and JSON feed

---

layouts/GlobalLayout.vue

fix: text overflow on the mobile

---

index.js

feat: deprecate modifyBlogPluginOptions

---

docs/config/README.md

**Summary**
prevText is 上一頁, not 下一頁
and
nextText is 下一頁, not 上一頁

docs: fix typo in globalPagination 

---

docs/config/README.md

docs: add missed comma in the example conf

---

components/Footer.vue
docs/config/README.md
example/.vuepress/config.js

**Summary**
I've checked out [vue-feather-icons](https://vue-feather-icons.netlify.com/) and pick up all the useful icons.

feat: add several contact types (close #69)

---

docs/config/palette.md

docs: fix typo

---

global-components/BaseListLayout.vue

fix: ssr hydration error on excerpt summary (fix #89)

---

docs/config/README.md

docs: fixes typo

---

docs/config/README.md

docs: add a ref for setting Disqus shortname

---

components/Feed.vue

fix: web feed link 404 when set custom base

---

components/Footer.vue
docs/config/README.md
example/.vuepress/config.js

**Summary**
Fix #105 
Related PR #110 
**Background**: It sounds weird to enforce users give it a link.
**AS-IS**:
> footer.copyright
> - Type: Array<{ text: string, link: string }>
> - Default: undefined
**Goal**:
> footer.copyright
> - Type: Array<{ text: string, link?: string }>
> - Default: undefined
To avoid …

fix: support copyright without link (fix #105)
